spring:
  datasource:
    url: jdbc:mysql://localhost:3306/njutkd?characterEncoding=UTF-8
    username: root
    password: zsy999666.
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 200
    max-idle: 20
    min-idle: 10
  thymeleaf:
    cache: false
